spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.3.100:3306/gulimall_pms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tJgrLtrjV8CYPeXd3Vj
      secret-key: pCy6jbPIrParR5rrysS5AT1bAdgymp
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com

  thymeleaf:
    cache: false

  redis:
    host: 192.168.3.100

# spring.cache.type=redis
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true  # 设置为ture，可以解决缓存穿透问题
    #  key-prefix: CACHE_
      use-key-prefix: true







  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.atguigu.gulimall: debug

gulimall:
  thread:
    core-size: 30
    keep-alive-time: 15
    max-size: 50 # 注意要比core-size大，否则报异常
