server:
  port: 20000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  thymeleaf:
    cache: false

  redis:
    host: 192.168.3.100
#      config:
#        server-addr: 127.0.0.1:8848
#        namespace: 8a9d26cb-f80c-4b2f-9a1d-00c72ef36316

#  application:
#    name: gulimall-auth-server
